language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - windows
  - osx
dist: xenial
git:
  submodules: false
before_install:
  - git submodule update --init --depth 1 --progress
  - echo $LANG
  - echo $LC_ALL
  - |
    if [ $TRAVIS_OS_NAME == linux ];
    then sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev \
      libpcre3-dev libmad0-dev libfluidsynth-dev libdumb1-dev libvorbis-dev libportmidi-dev clang-tidy;
    fi
  - |
    if [ $TRAVIS_OS_NAME == windows ];
    then
      declare -x DEPS_FILENAME=windows_dependencies_v4.zip;
      curl -LO https://github.com/coelckers/prboom-plus/releases/download/windows_dependencies/${DEPS_FILENAME};
      7z x ${DEPS_FILENAME} -o..;
    fi
  - |
    if [ $TRAVIS_OS_NAME == osx ];
    then 
      brew install sdl2 sdl2_image sdl2_mixer sdl2_net pcre mad fluidsynth dumb portmidi llvm;
      sudo ln -s "$(brew --prefix llvm)/bin/clang-tidy" /usr/local/bin/clang-tidy;
    fi
  - mkdir build
  - cmake -DCMAKE_BUILD_TYPE=Release -Wno-dev -B build prboom2
  - cmake --build build -j 9;

branches:
  only:
    - master
