[package]
name = "sounds_generator"
version = "0.1.0"
authors = ["kyle.coffey <kyle.coffey@tamu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
pom = "3.2"
nom = "6.1"

[build-dependencies]
bindgen = "0.57"
